title: <p align="center"> Mrunmayee Dixit </p>
<center><img src="assets/img/MyPhoto.JPG"/></center>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mrunmayee-dixit-7a89b2193/">LinkedIn</a> |
  <a href="https://github.com/mrunmayeedixit">GitHub</a>
  
  <br>   
  I'm working as Senior Data Engineer on Ideation, Solution design, AI/ML solutions, Spark, Machine learning , clasifiaction, clustering & NLP related problems.
  Also handing a team working on same.
  Working in LTI from 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal